#!/bin/sh

########################################################
#Takes a file path as an argument                      #
#Prints the largest files in the directory (top 10)    #
#Prints the total size of the directory                #
########################################################

usage () { echo "mydu <file directory>"; echo;}

if [ `uname -s` == 'Darwin' ] || [ `uname -s` == 'FreeBSD' ]; then
    echo "Human readable output is not currently supported on your system"
    echo
    DU="du -ac"
    SORT="sort -nr"
else
    DU="du -ha"
    SORT="sort -hr"
fi

if [ ! $# == 1 ]; then  
    usage
    exit

else
    DIRECTORY="$1"
    if [ -d $DIRECTORY ]; then
        $DU $DIRECTORY 2> /dev/null|$SORT|awk '
        {
            count = 0
            while(getline == 1 && count != 11){
                if (count == 0)
                    print "Total Size: " $1
                else
                    print $1, $2 
                    count = count + 1
            }
        }
    '| head -11

    else
        echo "Directory not found"
        exit
    fi
fi
