#!/bin/bash

########################################################
#Takes a file path as an argument                      #
#Prints the largest files in the directory (top 10)    #
#Prints the total size of the directory                #
########################################################

usage () { echo "mydu <file directory>"; echo;}

if [ `uname -s` == 'Darwin' ]; then
    echo "Human readable output is not currently supported on Mac"
    echo
    DU="du -ac"
    SORT="sort -nr"
else
    DU="du -ha"
    SORT="sort -hr"
fi

if [ ! $# == 1 ]; then  
    usage
    exit
else

DIRECTORY="$1"
if [ -d $DIRECTORY ]; then
    $DU $DIRECTORY 2> /dev/null|$SORT|awk '
    {
        print "Total Size: " $1
        file_count=0
        while(getline == 1){
            print $1, $2 
            file_count = file_count + 1
        }
    }
    END{"File Count:" file_count}
'| head -11
else
   echo "Directory not found"
   exit
fi
fi
